
# File: .github/workflows/ci.yml
name: Build & Test Cowsay SI

on:
  push:
    branches:
      - test
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1) Grab your code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2) Build the Docker image
      - name: Build Docker image
        run: |
          docker build \
            --tag cowsay-si:ci \
            --file ./Dockerfile \
            .

   # 3) Start the container in the background
      - name: Start container
        id: start
        run: |
          CONTAINER_ID=$(docker run -d -p 8080:8080 cowsay-si:ci 8080)
          echo "::set-output name=id::$CONTAINER_ID"

      # 4) Wait for it to boot
      - name: Wait for server
        run: sleep 5

      # 5) Hit the endpoint and save the response
      - name: Smoke-test endpoint
        run: |
          curl -s http://localhost:8080/Hello%20from%20GitHub%20Actions! > response.txt

      # 6) Stop the container
      - name: Stop container
        run: docker kill ${{ steps.start.outputs.id }}

      # 7) Validate the response contains our message
      - name: Validate output
        run: |
          if grep -q "Hello from GitHub Actions!" response.txt; then
            echo "✅ Smoke test passed!"
          else
            echo "❌ Smoke test failed!"
            exit 1
          fi
