on:
  push:
    branches:
      - test      # ← only trigger on pushes to “test”
  workflow_dispatch:  # optional: lets you run it manually on test
  
  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag image
        run: |
          docker tag cowsay-si:ci \
            ${{ secrets.DOCKERHUB_USERNAME }}/cowsay-si:latest

      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/cowsay-si:latest

      - name: Pull & verify
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cowsay-si:latest
