name: Cowsay SI CI

on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            --tag cowsay-si:ci \
            --file ./Dockerfile \
            .

      - name: Start container
        id: start
        run: |
          CONTAINER_ID=$(docker run -d -p 8080:8080 cowsay-si:ci 8080)
          echo "::set-output name=id::$CONTAINER_ID"

      - name: Wait for server
        run: sleep 5

      - name: Smoke-test endpoint
        run: |
          curl --fail --silent "http://localhost:8080/Hello%20from%20GitHub%20Actions!" \
            > response.txt

      - name: Stop container
        run: docker kill ${{ steps.start.outputs.id }}

      - name: Verify output
        run: grep -q "Hello from GitHub Actions!" response.txt

  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cowsay-si:ci

      - name: Pull back & verify image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cowsay-si:ci
